### ISSUE TITLE
undefined method `prepend_environment_path' for GLib:Module (NoMethodError)

### ISSUE THREAD

**Issue by tomor** [veny/dumon#18]
Hi, 
can you tell me whats wrong?

I've installed dumon via "sudo gem install dumon". Instalation finished ok.

When I run dumon I get:
```
tomor@tomor-t530:~$ dumon
/var/lib/gems/1.9.1/gems/gtk2-1.2.6/lib/gtk2/base.rb:20:in `<top (required)>': undefined method `prepend_environment_path' for GLib:Mo
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/gtk2-1.2.6/lib/gtk2.rb:11:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/dumon-0.2.8/lib/dumon.rb:5:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/dumon-0.2.8/bin/dumon:3:in `<top (required)>'
        from /usr/local/bin/dumon:23:in `load'
        from /usr/local/bin/dumon:23:in `<main>'
```

```
tomor@tomor-t530:~$ gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 1.8.23
  - RUBY VERSION: 1.9.3 (2012-04-20 patchlevel 194) [x86_64-linux]
  - INSTALLATION DIRECTORY: /var/lib/gems/1.9.1
  - RUBY EXECUTABLE: /usr/bin/ruby1.9.1
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/1.9.1
     - /home/tomor/.gem/ruby/1.9.1
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :benchmark => false
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - http://rubygems.org/
```

**Comment by veny** [comment]
fixed in 0.3.0 by upgrade to Ruby gtk 2.2+

working with  gtk2-2.24.27, ruby 2.3.0dev, ruby gtk2-2.2.4
